# Generated by Django 3.2.5 on 2021-10-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTIN', models.BigIntegerField()),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
                ('mrp', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outsider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('clientID', models.BigIntegerField()),
                ('GTIN', models.BigIntegerField()),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
                ('mrp', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=500)),
                ('pin', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('outsider', models.ManyToManyField(to='webapp.Outsider')),
                ('product', models.ManyToManyField(to='webapp.Product')),
            ],
        ),
    ]
