# Generated by Django 3.2.5 on 2021-10-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allorders',
            name='outsider',
        ),
        migrations.AlterField(
            model_name='allorders',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='outsider',
            name='clientID',
            field=models.BigIntegerField(default=0),
        ),
    ]
